import { Azeret_Mono } from "next/font/google"
import "./globals.css"

const azaret_mono = Azeret_Mono({ subsets: ["latin"] })

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
     <html lang="en" >
       <body>{children}</body>
     </html>
   )
 }
