import { Azeret_Mono } from "next/font/google"

import "../app/styles/globals.css"

const azaret_mono = Azeret_Mono({
  subsets: ["latin"],
  weight: ['800','400'],
})

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={azaret_mono.className}>
     <body>{children}</body>
    </html>
  )
}